package configs

func LoadRegisterSites() []string {
	return []string{
		// "https://www.snapptrip.com/?login_step=phone-number",
		// "https://www.mihmansho.com/application",
		"https://app.snapp-box.com/login",
		"https://experts.achareh.co/",
		// "https://app.alopeyk.com/register",
		// "https://sanjagh.pro/login",
		// "https://m.homeservize.com/auth",
		// "https://bimebazar.com/login/?next=%2F",
		// "https://web.wepod.ir/signup/mobile",
		// "https://panel.invex.ir/auth/register",
		// "https://web.appetit.fit/auth/login",
		// "https://neshan.org/maps#c29.630-52.524-16z-0p",
		// "https://www.anten.ir/profile",
		// "https://subchin.ir/auth",
		// "https://web.changaal.com/",
		// "https://ghabzino.com/login",
		// "https://app.mydigipay.com/auth/login",
		// "https://itoll.com/",
		// "https://pwa.tara.mobi/login?prevPage=onboard",
		// "https://balad.ir/#10/35.6995/51.412",
		// "https://www.zarehbin.com/signin",
		// "https://gerdoo.net/account/",
		"https://www.filimo.com/signin",
		// "https://filmnet.ir/login?redirect=/login",
		// "https://taaghche.com/login",
		"https://www.sheyda.com/auth",
		// "https://www.namava.ir/register",
		"https://www.melkfori.com/Register",
		// "https://didanist.com/user/profile",
		// "https://www.technolife.com/account/Login?backTo=/",
		// "https://market.pinket.com/login",
		// "https://bazargam.com/login/",
		// "https://www.okala.com/auth",
		// "https://ketabnak.com/login",
		// "https://panel.appeto.ir/send-otp",
		// "https://book.icfi.ir/account/registration",
		// "https://radinpayamak.com/login/",
		// "https://www.setka724.ir/cs/UserMgmt/17",
		// "https://nikepars.com/%DA%A9%D8%AF-%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF%DB%8C/",
		// "https://web.igap.net/",
		// "https://web.eitaa.com/",
		// "https://web.rubika.ir/",
		// "https://kala.sfara.ir/",
		// "https://web.shad.ir/#/login",
		// "https://my.mci.ir/auth",
		// "https://static-ebcom.mci.ir/ecm/ewano/pwa/login?backUrl=",
		"https://cafebazaar.ir/signin",
		// "https://doctor-yab.ir/Users/login/",
		// "https://app.herlife.app/join",
		// "https://aramia.me/login",
		// "https://office.mizito.ir/#/register/p=/s1",
		// "https://jaryan.app/",
		"https://web.baazar.ir/",
		// "https://www.weblite.me/",
		// "https://app.top.ir/login",
		// "https://app.isfahan.ir/signin",
		// "https://separ-pwa.sanaap.co/signin",
		// "https://tv.sheyda.com/login",
		// "https://web.nasimrezvan.com/",
		// "https://tabdeal.org/auth/register-req",
		// "https://app.fardaco.com/account/login-by-mobile",
		// "https://torob.com/user/",
		// "https://talasea.ir/login/login-otp",
		// "https://adinapp.ir/web/",
		// "https://join.tapsi.ir/driver",
		// "https://join.tapsi.ir/biker",
		// "https://gate.telewebion.com/user",
		"https://app.zigap.ir/user/auth",
		// "https://chatgptiran.com/user/register/",
		// "https://web.ivira.ai/#/login",
		// "https://hooshang.ai/",
		"https://app.nazdika.com/",
		"https://web.gap.im/",
		// "https://web.balonet.net/#/auth",
		// "https://www.alibaba.ir/app#d-auth",
		"https://host.jabama.com/",
		// "https://www.flytoday.ir/sign-in",
		// "https://www.otaghak.com/",
		// "https://www.tcharter.ir/flight",
		// "https://mrbilit.com/profile",
		// "https://www.jajiga.com/",
		// "https://www.eghamat24.com/#m-login-or-register",
		// "https://auth.roocket.ir/login",
		// "https://sms.ir/panel/",
		// "https://www.melipayamak.com/",
		"https://account.amootsoft.com/Account/SignIn",
		// "https://payamito.com/sms-register-page/",
		// "https://asanak.com/",
		// "https://app.sms1.ir/register",
		// "https://www.mopon.ir/%D8%AB%D8%A8%D8%AA-%D9%86%D8%A7%D9%85-%D8%AF%D8%B1-%D9%85%D9%88%D9%BE%D9%86",
		// "https://www.offch.com/login",
		// "https://signin.irancell.ir/signin",
		// "https://seller.digikala.com/pwa/account/sign-in",
		// "https://iranecar.com/login",
		"https://www.yasertebat.com/login/?loginStatus=3",
		// "https://www.didogram.com/auth/",
		// "https://dadbanan.com/auth",
		// "https://www.shab.ir/login",
		// "https://hamrahtel.com/login",
		// "https://nan.ac/login",
		"https://bargheman.com/auth",
		// "https://shafadoc.ir/fa/register",
		// "https://loganshop1.com/register/",
		// "https://www.iranketab.ir/auth",
		// "https://www.ics.ir/fa/login",
		// "https://reyhandept.com/auth/",
		// "https://ketabnoush.ir/login",
		"https://datasabt.ir/login/datayar",
		"https://www.zhaket.com/login?afterLogin=%2F",
		// "https://enobat.tbzmed.ac.ir/Account/PhoneLogin",
		// "https://book.afaq-lc.com/my-account/",
		// "https://emrooz.ir/auth",
		// "https://emp.e-estekhdam.com/login",
		// "https://iranhoma.com/login-signup/",
		"https://app.filimo.school/auth",
		// "https://sadeghloo.academy/logincheck",
		"https://didar24.com/login",
		// "https://eshop.ncc.gov.ir/password/reset",
		"https://melligold.com/pwa/account",
		// "https://login.myids.ir/digiform/login",
		// "https://faresbazar.com/register",
		// "https://account.jobvision.ir/Candidate",
		// "https://shokrino.com/otino/",
		// "https://www.shahidpalizvani.ir/login",
		// "https://abantether.com/register",
		// "https://www.riiha.ir/login",
		// "https://samaaryanic.com/login-register/",
		// "https://azmoonkheilisabz.com/register",
		// "https://roomeet.ir/auth/forget-password/",
		// "https://www.novin.com/auth/",
		"https://bonyadonline.com/site/register",
		// "https://panel.classino.com/auth",
		"https://avacoach.ir/user/login-mobile",
		// "https://app.tetherland.com/login",
		// "https://maskanplus.ir/auth",
		// "https://1shoo.ir/login-register/",
		// "https://behandam.kermany.com/#/auth",
		// "https://instachap.com/account/login",
		// "https://www.1mohtava.com/signin",
		// "https://zmam.ir/Login",
		"https://vency.ir/auth/login",
		// "https://eservices.cspf.ir/Auth-api/auth/register/step-1",
		// "https://chekida.com/account/log-in",
		// "https://khodro45.com/auth/login/",
		// "https://vinsign.ir/signin",
		// "https://shenoto.com/auth",
		// "https://www.portal.ir/login",
		// "https://www.atrafshan.ir/user/login-register",
		// "https://accounts.hyperstariran.ir/Account/Login",
		// "http://185.117.139.168/Account/SignUp",
		// "https://www.booking.ir/sign-in/",
		// "https://kheilisabz360.com/login",
		// "https://neshan.org/maps#c35.689-51.389-11z-0p",
		// "https://join.tapsi.ir/driver?utm_source=Home-Page&utm_medium=Top-Banner&utm_campaign=D-ACQ",
		// "https://nasrinaghvami.com/code/",
		// "https://web.bale.ai/login?redirectTo=/chat",
		// "https://app.ozone.ir/sign-in",
		// "https://web.splus.ir/",
		// "https://bonyani.ir/fa/auth/login",
		// "https://gate.telewebion.com/user?redirect=https://telewebion.com/tags/0x1b1dd3b#null",
		// "https://www.otaghak.com/#:R2am:",
		// "https://www.jajiga.com",
		// "https://digimaze.org/login",
		// "https://account.jobvision.ir/Candidate?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DJobVisionAngularClient%26redirect_uri%3Dhttps%253A%252F%252Fjobvision.ir%252Fauth-callback%26response_type%3Did_token%2520token%26scope%3Dopenid%2520profile%2520JobVisionApi%2520roles%2520offline_access%2520IdentityServerApi%26nonce%3De03c7505f2800d3c4d51c2e2290bec26aagSLXoKT%26state%3Df5f444a1541778756190987be3b53facefXMHiOZW%26role",
		"https://app.jetbarco.ir/login",
		// "https://www.boomerangev.com/site/signin",
		// "https://www.alibaba.ir/invitation",
		// "https://milli.gold/app/login?stepper=login-form",
		// "https://app.mahta.co/fa/auth/login",
		// "https://web.iminoapp.com/",
		// "https://datasabt.ir/login/datayar?Redirect=/account/",
		// "https://iranhoma.com/login-signup/?backto=https://iranhoma.com/my-account/",
		"https://didar24.com/login?redirect=/ofogh",
		// "https://login.myids.ir/digiform/login?",
		// "https://auth.digikala.com/realms/dk-group/protocol/openid-connect/auth?client_id=digikala-web-public&redirect_uri=https%3A%2F%2Fwww.digikala.com%2Fsso-redirect%2F%3Fback-url%3D%252Fprofile%252F&state=dbaf9562-757b-4d9b-ac1c-ff4eddc16b54&response_mode=fragment&response_type=code&scope=openid&nonce=77ffd6b4-5671-4db7-a44f-0fe8b8f20ed6&code_challenge=okmLc7DVz5f9QuXBcqyAwyTBnX2_kuoa2Vjg08AND1s&code_challenge_method=S256",
		// "https://www.riiha.ir/login?redirectUrl=%2Fproduct%2Fra-8872%2F%D8%A8%D8%A7%D9%84%D9%85-%D9%85%D8%BA%D8%B0%DB%8C-%D9%84%D8%A8-%D9%86%D9%88%D8%AF-lip-balm-nude",
		// "https://behandam.kermany.com/#/auth?ref=%2Flist%2Fview",
		// "https://instachap.com/account/login?ReturnUrl=%2Fprofile%2Fmyorders",
		"https://biomaze.ir/login",
		"https://vency.ir/auth/login?redirectUrl=https:%2F%2Fvency.ir%2Fpanel%2Fuser%2Fhome",
		// "https://chekida.com/account/log-in?next=/my-library/",
		// "https://www.portal.ir/login?next=%2Fregister",
		"https://www.atrafshan.ir/user/login-register?back=%252F",
		// "https://accounts.hyperstariran.ir/Account/Login?ReturnUrl=%2F",
	}
}

func LoadFillSites() []string {
	return []string{
		"https://noafarinan.com/consulting/form/",
		"https://zeusir.com/contactus.aspx",
		"https://pouyalanguage.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%B1%D8%A7%DB%8C%DA%AF%D8%A7%D9%86/",
		"https://elienglish.com/contact-us/",
		"https://pafcoerp.com/public/reqdemo.html",
		"https://www.mahzoon.com/main/contactus/",
		"https://paresh.ir/contact-us",
		"https://www.gamas20.com/%d8%af%d8%b1%d8%ae%d9%88%d8%a7%d8%b3%d8%aa-%d9%85%d8%b4%d8%a7%d9%88%d8%b1%d9%87/",
		"https://nikmaneshedu.ir/#consultant",
		"https://onlinepersianschool.com/registration/",
		"https://advising-matro.ir/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AA%D9%84%D9%81%D9%86%DB%8C-%D9%88-%D8%A2%D9%86%D9%84%D8%A7%DB%8C%D9%86/",
		"https://dr-arashrezaei.com/free-consulting-registeration/",
		"https://persiananimation.com/consultation/",
		"https://www.kalishop.ir/site/contact",
		"https://rayandigit.ir/forms/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AE%D8%B1%DB%8C%D8%AF",
		"https://mehdiparvini.com/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D9%81%D8%B1%D8%AF%DB%8C-%DB%8C%D8%A7-%D8%B3%D8%A7%D8%B2%D9%85%D8%A7%D9%86%DB%8C/step01/",
		"https://noorekherad.com/consultation-request/",
		"https://safirmashad.com/",
		"https://ariadanesh.com/request/",
		"https://maharatjoo.net/site/consultation",
		"https://www.ircambridge.com/contact/",
		"https://aticoacademy.com/contact-us/",
		"https://modirfa.com/application-form/",
		"https://baziboom.net/moshavere/",
		"https://vismanit.com/trial/",
		"https://kiatarh.com/consultation-request/",
		"https://heybati.com/product/درخواست-مشاوره/",
		"https://www.jonoub.ir/FA/Page/ConsultationRequest",
		"https://radsch.ir/home/branch/1/advicerequest",
		"https://nablearning.ir/تماس-با-ما/",
		"https://www.tamasmarket.com/site/contact",
		"https://ehasht.com/contact-us/",
		"https://www.dokmeha.com/request-a-consultation/",
		"https://ghazal.consulting/22consultation-request/",
		"https://www.spain-iran.ir/contact",
		"https://kaizenbcc.com/contact-us/",
		"https://mezure.ir/contact/",
		"https://visamaze.ir/consultation-request/",
		"https://hassanetaat.com/consulting/",
		"https://pashamohammadreza.ir/consultation-request/",
		"https://modirenovin.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%B3%DB%8C%D8%B3%D8%AA%D9%85-%D8%B3%D8%A7%D8%B2%DB%8C-%DA%A9%D8%B3%D8%A8-%D9%88%DA%A9%D8%A7%D8%B1/",
		"https://www.serviceiran.com/contact-us/",
		"https://hamiconsulting.ir/consultation-form/",
		"https://aryanbusinessacademy.com/request-consultation/",
		"https://tosedanesh.com/contact-us/",
		"https://parsdigital.com/consultation/",
		"https://nikaacademy.com/request-consultation/",
		"https://soroushit.com/contact-us/",
		"https://mihanbusiness.com/consultation-request/",
		"https://baranedu.com/request-advice/",
		"https://technova.ir/consultation-form/",
		"https://kanoonfarda.com/request-consultation/",
		"https://emkansabt.com/en/contact-us/",
		"https://oni-group.com/en/contact/",
		"https://arianaapply.com/free-consultation-form/",
		"https://nitrosell.ir/c/",
		"https://dartehran.com/contact-us/",
		"https://kaniran.org/en/contact-us/",
		"https://selltoiran.com/en/contact-us/",
		"https://iranianoffice.com/contact/",
		"https://iranrequest.com/offers/",
		"https://robina.ir/contact-us/",
		"https://iranbizcoach.com/consultation/",
		"https://hamyarmanager.com/request-consulting/",
		"https://karafarinbartar.ir/contact/",
		"https://fekrbartar.com/consultation-form/",
		"https://daneshmodir.ir/request-consultation/",
		"https://ideapardazan.com/contact-us/",
		"https://rahnamaco.com/consultation-request/",
		"https://modirplus.com/contact/",
		"https://tossegar.ir/consultation/",
		"https://karino.biz/contact-us/",
		"https://brandtalk.ir/consultation/",
		"https://hamyarsystem.com/contact/",
		"https://arshaco.ir/request-consultation/",
		"https://strategicmind.ir/contact-us/",
		"https://karafarinsho.com/consultation/",
		"https://rayamodir.com/request-advice/",
		"https://behinesaz.ir/contact/",
		"https://afzarsystem.com/consultation/",
		"https://modiraneiran.com/contact-us/",
		"https://rahnamarket.com/consultation-request/",
		"https://www.novin.com/contact-us/",
		"https://zeus.ir/consulting",
		"https://seoedu.ir/contact/",
		"https://karnakon.ir/business-consulting-form/",
		"https://danup.ir/contact/",
		"https://www.roshdana.com/tr/",
		"https://melalinstitute.com/consultation",
		"https://melalinstitute.com/contact-us",
		"https://www.ircambridge.com/contact/",
		"https://danup.ir/teacher/reza-hosseinzadeh/?login=true&page=1&redirect_to=https%3A%2F%2Fdanup.ir%2Fteacher%2Freza-hosseinzadeh%2F",
		"https://maktabkhooneh.org/contactus/",
		"https://dourkhiz.com/",
		"https://hamkadeh.com/",
		"https://notruphil.com/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%DA%A9%D9%86%DA%A9%D9%88%D8%B1/",
		"https://simiaroom.com/",
		"https://ravanban.com/",
		"https://iranianpsychology.com/",
		"https://decorbax.com/%D9%86%DB%8C%D8%A7%D8%B2-%D8%A8%D9%87-%D8%B7%D8%B1%D8%A7%D8%AD%DB%8C-%D8%AF%D8%A7%D8%B1%DB%8C%D8%AF%D8%9F%D9%81%D8%B1%D9%85-%D8%B1%D8%A7-%D9%BE%D8%B1-%DA%A9%D9%86%DB%8C%D8%AF-%D8%AA%D8%A7-%D8%A8%D8%A7/",
		"https://gazellecg.com/consultation-request/",
		"https://matinatlas.ir/consultation-order-registration/",
		"https://mizbantel.ir/telephone-consultation-panel/",
		"https://nexfon.ir/free-consultation-form/",
		"https://www.ksykg.com/free-consultation-request-form/",
		"https://www.khaneyebrandsazi.ir/consulting-form/",
		"https://digiform.ir/copy/df9a9b67c",
		"https://zibapack.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D9%86%D8%A7%D8%AE%D9%86/",
		"https://www.websitebartar.com/consultation-request-form/",
		"https://boofagency.ir/advice-request/",
		"https://maharatjoo.net/site/consultation",
		"https://docs.google.com/forms/d/e/1FAIpQLScVw6IWD2y6_YBTroBr4fKf96_AVyuzLfx_93bQAJ9Nk1HNHg/viewform?pli=1",
		"https://pmlm.ir/fa/consultationForm/a2",
		"https://kamrany-academy.com/%D9%81%D8%B1%D9%85-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AA%D8%AE%D8%B5%D8%B5%DB%8C-%D9%BE%D9%88%D8%B3%D8%AA/",
		"https://mygene.ir/%D9%BE%D8%B1%D8%B3%D8%B4%D9%86%D8%A7%D9%85%D9%87-%D9%BE%D9%88%D8%B3%D8%AA/",
		"https://ptc.khu.ac.ir/frm/form",
		"https://pasargadmigration.com/%D9%81%D8%B1%D9%85-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://pouyalanguage.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%B1%D8%A7%DB%8C%DA%AF%D8%A7%D9%86/",
		"https://digi-exam.com/%D9%81%D8%B1%D9%85-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://autokhosravani.com/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AE%D8%B1%DB%8C%D8%AF-%D8%AE%D9%88%D8%AF%D8%B1%D9%88/",
		"https://masaelipack.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://www.ksykg.com/free-consultation-request-form/",
		"https://k-kh.com/advice-form/",
		"https://autolife.ir/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AE%D9%88%D8%AF%D8%B1%D9%88/",
		"https://www.physic-machine.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87",
		"https://danesheravaan.ir/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://www.hamdardi.com/%D9%81%D8%B1%D9%85-%D9%BE%D8%B1%D8%B3%D8%B4-%D9%85%D8%B1%D8%A7%D8%AC%D8%B9%D8%A7%D9%86%D8%8C-%D9%BE%D8%A7%D8%B3%D8%AE-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D8%A7%D9%86/",
		"https://www.behpackmachinery.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://mvmkaraj.com/sell-terms/",
		"https://png.linetoslice.com/s/stats",
		"https://yi.iau.ir/daneshjoei-farhangi/fa/form/301/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D9%BE%D8%B2%D8%B4%DA%A9%DB%8C-%D9%85%DA%A9%D8%A7%D8%AA%D8%A8%D9%87-%D8%A7%DB%8C",
		"https://www.medimedia.ir/tel",
		"https://holosen.net/call/",
		"https://alihadaf.com/request-a-telephone-consultation/",
		"https://melkisabti.ir/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%A8%D8%A7-%D9%88%DA%A9%DB%8C%D9%84/",
		"https://tarahanepooya.ir/form/2/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87",
		"https://nadiaborhan.com/consultation-forms/marketing-consultation-request-form",
		"https://afaghcenter.ir/request-free-advice/",
		"https://tyb.ir/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AA%D9%84%D9%81%D9%86%DB%8C/",
		"https://vakilekasbokar.ir/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AA%D9%84%D9%81%D9%86%DB%8C/",
		"https://mag.iranrahjoo.com/form/6/notificatiomform",
		"https://tamir-mobile.ir/request-repair-mobile/",
		"https://www.dourbord.ir/request-form/",
		"https://basparco.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://formafzar.com/form/02c7i",
		"https://behinpayam.com/call-request/",
		"https://jamejamam.ir/%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AA%D9%84%D9%81%D9%86%DB%8C-%D8%B1%D8%A7%DB%8C%DA%AF%D8%A7%D9%86/",
		"https://www.khaneyebrandsazi.ir/consulting-form/",
		"https://mobileland.online/repair-request-form/",
		"https://hifon.ir/phone-consultations/",
		"https://ariyaz.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://stu.iau.ir/fa/form/34/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D8%B1%D8%A7%D9%87%D9%86%D9%85%D8%A7%DB%8C%DB%8C-%D8%A7%D8%B2-%D9%85%D8%B4%D8%A7%D9%88%D8%B1",
		"https://asanito.com/professional-telephone-answering-system-step-by-step/",
		"https://rozegarekoodaki.com/advice.php",
		"https://eliteimmigrate.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AA%D9%84%D9%81%D9%86%DB%8C/",
		"https://blanton.store/consultation_request_form/",
		"https://forms.inif.ir/teladvice",
		"https://nikantel.com/telephone-counseling-center/",
		"https://www.ksykg.com/free-consultation-request-form/",
		"https://snapp.doctor/register-consultant/",
		"https://www.hesabrayan.com/contact/request-demo",
		"https://pafcoerp.com/public/reqdemo.html",
		"https://limaservice.ir/%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%86%D9%85%D8%A7%DB%8C%D9%86%D8%AF%DA%AF%DB%8C-%D8%A7%D8%B4%D8%AE%D8%A7%D8%B5-%D8%AD%D9%82%DB%8C%D9%82%DB%8C/",
		"https://www.emofid.com/investment-advice/",
		"https://irancell.ir/p/1590/contact-us/#form-contactus",
		"https://maher.ir/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D9%85%D8%A7%D9%87%D8%B1/",
		"https://kartaban.com/moshaverfori/",
		"https://khosravan.org/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://www.cfdcollege.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://modnoor.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D8%AE%D8%AF%D9%85%D8%A7%D8%AA-%D9%BE%D8%B3-%D8%A7%D8%B2-%D9%81%D8%B1%D9%88%D8%B4/",
		"https://manzino.ir/form-1",
		"https://www.parskhazar.com/customers-specifications-form/",
		"https://nncgs1.com/request/",
		"https://hbb-co.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%86%D9%85%D8%A7%DB%8C%D9%86%D8%AF%DA%AF%DB%8C-%D9%81%D8%B1%D9%88%D8%B4-%D9%88-%D8%AE%D8%AF%D9%85%D8%A7%D8%AA/",
		"https://aytack.com/requestagenc",
		"https://www.setaak.ir/fa/order-registration-form?srsltid=AfmBOoo3aP1HB-qebxvzLYX4LDT5Zy2HjSTI_ACvGNNUslHmWwNvotqb",
		"https://emdad24.com/repairman-request-form/",
		"https://blanton.store/application-form/",
		"https://ariadanesh.com/request/",
		"https://moshavertel.com/Free-Consultation-Service",
		"https://tilavclinic.com/consultation/",
		"https://afaghcenter.ir/request-free-advice/",
		"https://iranasiyab.com/%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%B1%D8%A7%DB%8C%DA%AF%D8%A7%D9%86/",
		"https://academyaghidat.com/%D9%81%D8%B1%D9%85-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%B1%D8%A7%DB%8C%DA%AF-%D8%A7%D9%86%D8%AF%D8%A7%D8%B2%DB%8C-%DA%A9%D8%B3%D8%A8-%D9%88-%DA%A9%D8%A7%D8%B1-%D8%A7%DB%8C%D9%86%D8%AA%D8%B1%D9%86%D8%AA/",
		"https://fullito.org/%D8%AA%D9%85%D8%A7%D8%B3-%D8%A8%D8%A7-%D9%81%D9%88%D9%84%DB%8C%D8%AA%D9%88/",
		"https://solalehschool.ir/FB/22/7A7B53926DFA4D5DB93ACBB60121E3E0/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D8%AC%D9%84%D8%B3%D9%87-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AA%D8%AD%D8%B5%DB%8C%D9%84%DB%8C-%D8%B1%D8%A7%DB%8C%DA%AF%D8%A7%D9%86",
		"https://www.cfdcollege.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://www.rad-iran.com/educational-counseling-form/",
		"https://aryaeducationgroup.com/%D9%81%D8%B1%D9%85-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AA%D8%AD%D8%B5%DB%8C%D9%84%DB%8C/",
		"https://khosravan.org/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://pezeshky.com/free-educational-counseling/",
		"https://mahramraz.com/%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AA%D8%AD%D8%B5%DB%8C%D9%84%DB%8C/",
		"https://www.rdss.org/%D9%81%D8%B1%D9%85_%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://ariadanesh.com/request/",
		"https://afaghcenter.ir/request-free-advice/",
		"https://www.kalishop.ir/moshaver",
		"https://maralhashemi.com/free-consultation-request-form/",
		"https://formafzar.com/form/jtj9g",
		"https://ghorbaniholding.com/kharid/",
		"https://www.osvehsanat.com/purchase-consultation-request/",
		"https://matinatlas.ir/consultation-order-registration/",
		"https://sharifgearbox.com/%D9%81%D8%B1%D9%85-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D9%81%D9%86%DB%8C-%DA%AF%DB%8C%D8%B1%D8%A8%DA%A9%D8%B3-%D8%B5%D9%86%D8%B9%D8%AA%DB%8C/",
		"https://behincg.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"http://app.didar.me/customer/form/3c4b1845-b138-4ad1-87cc-afb0668441b1",
		"https://www.tigerbio.com/%D9%81%D8%B1%D9%85-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87-%D8%AE%D8%B1%DB%8C%D8%AF/",
		"https://kazhwa.com/consultation-request-form/",
		"https://tarrah.website/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://khoshneshin.co/free-consultation-request-form/",
		"https://ieltswithparisa.com/consultation/",
		"https://maharatjoo.net/site/consultation",
		"https://phcst.com/%D9%81%D8%B1%D9%85-%D8%AB%D8%A8%D8%AA-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://portal.aradihe.com/Consultation",
		"https://irajsharafi.com/%D9%81%D8%B1%D9%85-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://nikmaneshedu.ir/reconsu/",
		"https://madresezendeginet.com/%D9%81%D8%B1%D9%85-%D8%AB%D8%A8%D8%AA-%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D8%B3%D8%AA-%D9%85%D8%B4%D8%A7%D9%88%D8%B1%D9%87/",
		"https://afaqstudent.com/request-form/",
		"https://hesabdarshid.com/guide-form/",
		"https://zarafza.com/investment-advice",
	}
}

type FormConfig struct {
	Fields map[string]string `json:"fields"`
}

type Config struct {
	HTTPTimeout int                    `json:"http_timeout"`
	Forms       map[string]*FormConfig `json:"forms"`
}

func DefaultConfig() *Config {
	return &Config{
		HTTPTimeout: 60,
		Forms:       make(map[string]*FormConfig),
	}
}

var PredefinedConfigs = map[string]map[string]string{
	"gov.ir": {
		"fullname":  "PHONE",
		"cellphone": "PHONE",
	},
	"shahrdari.ir": {
		"name":   "PHONE",
		"tel":    "PHONE",
		"mobile": "PHONE",
	},
}

func GetFieldConfig(host string) map[string]string {
	if config, ok := PredefinedConfigs[host]; ok {
		return config
	}
	return nil
}

// PhoneKeywords keywords for detecting phone fields
var PhoneKeywords = []string{
	"phone", "mobile", "tel", "cell", "shomare", "tamams",
	"تلفن", "موبایل", "تماس", "همراه", "call",
}

// NameKeywords keywords for detecting name fields
var NameKeywords = []string{
	"name", "family", "fname", "lname", "نام", "فامیلی", "خانوادگی", "هویت",
}

// EmailKeywords keywords for detecting email fields
var EmailKeywords = []string{
	"email", "mail", "پست", "ایمیل",
}

// MessageKeywords keywords for detecting message fields
var MessageKeywords = []string{
	"message", "body", "desc", "comment", "payam", "tozih", "پیام", "توضیح", "متن",
}

// SuccessKeywords keywords for detecting successful submission
var SuccessKeywords = []string{
	"gform_confirmation_message",
	"با تشکر", "موفقیت", "sent", "successfully",
	"دریافت شد", "ثبت شد", "ممنون", "ثبت نام", "success",
}

// ErrorKeywords keywords for detecting errors
var ErrorKeywords = []string{
	"gfield_error", "validation_error", "خطا در اعتبارسنجی",
}

// PersianFirstNames list of Persian first names
var PersianFirstNames = []string{
	"علی", "محمد", "حسین", "رضا", "امیر", "سعید", "مهدی",
	"فاطمه", "زهرا", "مریم", "سارا", "نرگس",
}

// PersianLastNames list of Persian last names
var PersianLastNames = []string{
	"محمدی", "حسینی", "رضایی", "احمدی", "کریمی", "موسوی", "هاشمی", "جعفری", "صادقی", "نوری",
}

// IFrameKeywords keywords for detecting form builder iframes
var IFrameKeywords = []string{
	"form", "didar", "formafzar",
}
